#!/bin/bash

MDPADMIN="admin24"

# Demande de saisie du nom utilisateur et du poste de travail
echo "Entrez votre nom:"
read NOM_UTILISATEUR

echo "Le nom de votre poste de travail:"
read NOM_POSTE_DE_TRAVAIL

# Vérifie si l'utilisateur existe déjà
while grep -q "^$NOM_UTILISATEUR:" /etc/passwd; do
    echo "L'utilisateur $NOM_UTILISATEUR existe déjà, veuillez choisir un autre nom"
    read NOM_UTILISATEUR
done

# Création du répertoire de bienvenue dans le home de l'utilisateur
UTILISATEUR_HOME="/home/$NOM_UTILISATEUR/Bienvenue"

# Crée un utilisateur sans mot de passe avec l'option --allow-bad-names si nécessaire
sudo adduser --quiet --disabled-password --gecos "" --allow-bad-names "$NOM_UTILISATEUR"

# Crée le dossier de bienvenue
sudo mkdir -p "$UTILISATEUR_HOME"
sudo touch "$UTILISATEUR_HOME/fichier.txt"

    # Change le propriétaire du répertoire et du fichier
sudo chown "$NOM_UTILISATEUR:$NOM_UTILISATEUR" "$UTILISATEUR_HOME"
sudo chmod u+rwx "$UTILISATEUR_HOME"
sudo chmod u+rwx "$UTILISATEUR_HOME/fichier.txt""

# Ajouter des informations dans fichier.txt
echo "Bienvenue $NOM_UTILISATEUR" > "$UTILISATEUR_HOME/fichier.txt"
# Ajout de l'adresse IP à fichier.txt
ip addr show | grep "inet" | awk '{print$2}' | cut -d/ -f1 >> "$UTILISATEUR_HOME/fichier.txt"
echo "Votre poste de travail est $NOM_POSTE_DE_TRAVAIL" >> "$UTILISATEUR_HOME/fichier.txt"

# Message de confirmation
echo "Utilisateur $NOM_UTILISATEUR créé avec succès et répertoire de bienvenue configuré."

# Affichage du contenu du fichier
cat "$UTILISATEUR_HOME/fichier.txt"

